// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtkDHtGQGHOn8LvVcdAhOF-uN_Y-lb4cI',
    appId: '1:357826746533:web:fcd625909832ca3cefd54c',
    messagingSenderId: '357826746533',
    projectId: 'cryptonia-f5bc2',
    authDomain: 'cryptonia-f5bc2.firebaseapp.com',
    storageBucket: 'cryptonia-f5bc2.firebasestorage.app',
    measurementId: 'G-K92NEBJBY1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDh4ePKqkr9p82vexkY3LMOQ2pFlwNR_cY',
    appId: '1:357826746533:android:d70348f691dd9769efd54c',
    messagingSenderId: '357826746533',
    projectId: 'cryptonia-f5bc2',
    storageBucket: 'cryptonia-f5bc2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAn6Zfj8JFg7TehtheFP3VgMv5xrA2JBEM',
    appId: '1:357826746533:ios:ab6a0933d34ea1aaefd54c',
    messagingSenderId: '357826746533',
    projectId: 'cryptonia-f5bc2',
    storageBucket: 'cryptonia-f5bc2.firebasestorage.app',
    iosBundleId: 'com.getcryptonia.cryptonia',
  );
}
